Running Move unit tests
[ FAIL    ] 0x1::B::failing_test
[ PASS    ] 0x1::M::dummy_test

Test failures:

Failures in 0x1::B:

┌── failing_test ──────
│ Test was not expected to error, but it aborted with code 0 originating in an unknown location rooted here
└──────────────────

Test result: FAILED. Total tests: 2; passed: 1; failed: 1
