Running Move unit tests
[ PASS    ] 0x1::Module::other_module_aborts
[ PASS    ] 0x1::Module::tests_a
[ PASS    ] 0x1::Module::tests_aborts
[ PASS    ] 0x1::Module::tests_b
[ PASS    ] 0x1::Module::tests_c
[ FAIL    ] 0x1::Module::tests_d

Test failures:

Failures in 0x1::Module:

┌── tests_d ──────
│ Test was not expected to error, but it aborted with code 3 originating in an unknown location rooted here
└──────────────────

Test result: FAILED. Total tests: 6; passed: 5; failed: 1
